apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
  namespace: flask-app
spec:
  selector:
    app: flask-k8s
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer
